### ISSUE TITLE
ERROR! the role 'shadowman.reports.build_report_linux' was not found

### ISSUE THREAD

**Issue by dusmeyenlabut** [shadowman-lab/shadowman.reports#2]
I am new to Ansible so my questions could be no sense for you :) 
I tried to build the report linux role but I am getting this error.

ERROR! the role 'shadowman.reports.build_report_linux' was not found in /etc/ansible/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/etc/ansible

The error appears to be in '/etc/ansible/create-report.yaml': line 23, column 15, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      ansible.builtin.include_role:
        name: shadowman.reports.build_report_linux
              ^ here

**Comment by adworjan** [comment]
You need to install the collection (either inside your EE or onto your ansible server) in order to leverage that role
